# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 14:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=30)),
                ('static_share_id', models.CharField(default='', max_length=30)),
                ('session_share_id', models.CharField(default='', max_length=30)),
                ('session_expire', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LockAbsVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_inner_id', models.CharField(max_length=30)),
                ('is_opened', models.BooleanField(default=True)),
                ('orientation', models.CharField(default='left', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs_user_binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('binded_locks', models.ManyToManyField(to='portal.Lock')),
            ],
        ),
        migrations.AddField(
            model_name='lock',
            name='binded_abs_lock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.LockAbsVal'),
        ),
    ]
