# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='session_expire',
            field=models.DateTimeField(default=None),
        ),
    ]
