# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20160903_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='session_expire_readable',
            field=models.CharField(default='', max_length=50),
        ),
    ]
