# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_lock_session_expire_readable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='binded_abs_lock',
            new_name='absLockBinding',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='session_expire',
            new_name='sessionExpire',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='session_expire_readable',
            new_name='sessionExpireRreadable',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='session_share_id',
            new_name='sessionShareId',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='static_share_id',
            new_name='staticShareId',
        ),
        migrations.RenameField(
            model_name='lockabsval',
            old_name='is_opened',
            new_name='isOpened',
        ),
        migrations.RenameField(
            model_name='lockabsval',
            old_name='lock_inner_id',
            new_name='lockInnerId',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='abs_user_binding',
            new_name='bindedAbsUser',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='binded_locks',
            new_name='bindedLocks',
        ),
    ]
