# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20160905_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='absLockBinding',
            new_name='absoluteLockBinding',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='sessionShareId',
            new_name='sessionShareID',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='staticShareId',
            new_name='staticShareID',
        ),
        migrations.RenameField(
            model_name='lockabsval',
            old_name='lockInnerId',
            new_name='lockInnerID',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='bindedAbsUser',
            new_name='bindedAbsoluteUser',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='bindedLocks',
            new_name='bindedRelativeLocks',
        ),
    ]
