# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20160905_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='bindedAbsoluteLock',
            new_name='absoluteLockBinding',
        ),
    ]
