# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 15:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20160905_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='sessionExpire',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 5, 15, 12, 4, 546658, tzinfo=utc)),
        ),
    ]
