# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20160905_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='sessionExpire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
