# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20160806_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockabsval',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='lockabsval',
            name='lock_inner_id',
            field=models.CharField(max_length=16),
        ),
    ]
