# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20160807_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockabsval',
            name='lock_inner_id',
            field=models.CharField(max_length=20),
        ),
    ]
